name: flutter_jack
description: starter template made by @jslattery26
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_remote_config: ^4.2.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  cloud_functions: ^4.3.1
  firebase_analytics: ^10.4.1
  firebase_crashlytics: ^3.3.1
  firebase_messaging: ^14.6.1

  #riverpod-hooks-freezed
  hooks_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ^0.18.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  flutter_use: ^0.0.3

  #essentials
  logger: ^1.3.0
  uuid: ^3.0.7
  shared_preferences: ^2.1.1
  encrypt: ^5.0.1
  http: ^0.13.6
  go_router: ^7.0.2
  device_preview: ^1.1.0
  dynamic_color: ^1.6.5
  device_info_plus: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
